import { z } from 'zod';

const ChargeStateResponseSchema = z.object({
  response: z.object({
    battery_heater_on: z.boolean(),
    battery_level: z.number(),
    battery_range: z.number(),
    charge_amps: z.number(),
    charge_current_request: z.number(),
    charge_current_request_max: z.number(),
    charge_enable_request: z.boolean(),
    charge_energy_added: z.number(),
    charge_limit_soc: z.number(),
    charge_limit_soc_max: z.number(),
    charge_limit_soc_min: z.number(),
    charge_limit_soc_std: z.number(),
    charge_miles_added_ideal: z.number(),
    charge_miles_added_rated: z.number(),
    charge_port_cold_weather_mode: z.unknown(),
    charge_port_color: z.string(),
    charge_port_door_open: z.boolean(),
    charge_port_latch: z.string(),
    charge_rate: z.number(),
    charge_to_max_range: z.boolean(),
    charger_actual_current: z.number(),
    charger_phases: z.unknown(),
    charger_pilot_current: z.number(),
    charger_power: z.number(),
    charger_voltage: z.number(),
    charging_state: z.string(),
    conn_charge_cable: z.string(),
    est_battery_range: z.number(),
    fast_charger_brand: z.string(),
    fast_charger_present: z.boolean(),
    fast_charger_type: z.string(),
    ideal_battery_range: z.number(),
    managed_charging_active: z.boolean(),
    managed_charging_start_time: z.unknown(),
    managed_charging_user_canceled: z.boolean(),
    max_range_charge_counter: z.number(),
    minutes_to_full_charge: z.number(),
    not_enough_power_to_heat: z.boolean(),
    off_peak_charging_enabled: z.boolean(),
    off_peak_charging_times: z.string(),
    off_peak_hours_end_time: z.number(),
    preconditioning_enabled: z.boolean(),
    preconditioning_times: z.string(),
    scheduled_charging_mode: z.string(),
    scheduled_charging_pending: z.boolean(),
    scheduled_charging_start_time: z.unknown(),
    scheduled_charging_start_time_app: z.number(),
    scheduled_departure_time: z.number(),
    scheduled_departure_time_minutes: z.number(),
    supercharger_session_trip_planner: z.boolean(),
    time_to_full_charge: z.number(),
    timestamp: z.number(),
    trip_charging: z.boolean(),
    usable_battery_level: z.number(),
    user_charge_enable_request: z.unknown(),
  }),
});

export default ChargeStateResponseSchema;
